project:
  type: book
  output-dir: docs

book:
  title: "Experiments 2024"
  date: "January 2024"
  chapters:
    - index.qmd
    - 01-Experimentation.qmd
    - 02-CausalEffects.qmd
    - 03-ExperimentalDesign.qmd
    - 04-Uncertainty.qmd
    - 05-Visualization.qmd
    - 06-ethics.qmd
    - 07-FieldExperiments.qmd
  page-navigation: true
  sidebar:
    style: docked
    background: light
    foreground: darkblue

format:
  html:
    theme: yeti
    toc-title: Section Contents
    toc: true
    toc-location: left
    toc-depth: 4
    linkcolor: red
    hypothesis: true

  


editor: visual
